config/routes.rb
Rails.application.routes.draw do
  get      '/login',   to: 'sessions#new'
  post     '/login',   to: 'sessions#create'
  delete   '/logout',  to: 'sessions#destroy'

  root 'dashboard#index'
  resources :audiences
  resources :tasks do
    collection do
      get :active
      get :past
      get :user
      get :destination
      get :audience
    end
  end
  resources :event_contacts
  resources :media_items
  resources :destinations do
    collection do
      get :destination_type
    end
  end
  resources :destination_types
  resources :users
  resources :events do
    collection do
      get :active
      get :past
      get :planned
      get :unplanned
    end
  end
  resources :people_lists
  resources :tags
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/audience.rb
class Audience < ApplicationRecord

  def active_tasks
    return Task.audience_tasks(self)
  end
end

app/models/basic_entity.rb
class BasicEntity < ApplicationRecord
    self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :destination_type

  def active_tasks
    return Task.destination_tasks(self);
  end

end

app/models/destination_type.rb
class DestinationType < ApplicationRecord

  def destinations
    return Destination.where "destination_type_id = ?", self.id
  end
end

app/models/entity_tag.rb
class EntityTag < ApplicationRecord
  belongs_to :basic_entity
  belongs_to :tag
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :tasks

  def start_date_pretty
    return self.start_date.strftime("%m/%d/%Y")
  end

  def start_time_pretty
    return self.start_time.strftime("%I:%M:%S %p")
  end

  def start_date_and_time
    self.start_date && self.start_time ? self.start_date.strftime("%m/%d/%Y") + " " + self.start_time.strftime("%I:%M:%S %p") : ""
  end

  def end_date_pretty
    return self.end_date.strftime("%m/%d/%Y")
  end

  def end_time_pretty
    return self.end_time.strftime("%I:%M:%S %p")
  end

  def end_date_and_time
    return self.end_date.strftime("%m/%d/%Y") + " " + self.end_time.strftime("%I:%M:%S %p")
  end

  def days_to_start
    return self.start_date > Date.today ? (self.start_date - Date.today).to_i : 0;
  end

  def days_to_end
    return self.end_date > Date.today ? (self.end_date - Date.today).to_i : 0;
  end

  def self.active_events
    return Event.where "end_date >= ?", Date.today.to_date
  end

  def self.past_events
    return Event.where "end_date < ?", Date.today.to_date
  end

  def self.planned_events
    event_array = []
    Event.active_events.each do |active_event|
      if !active_event.tasks.blank? 
        event_array << active_event
      end
    end
    return event_array
  end

  def self.count_planned
    return Event.planned_events.count
  end

  def self.unplanned_events
    event_array = []
    Event.active_events.each do |active_event|
      if active_event.tasks.blank? 
        event_array << active_event
      end
    end
    return event_array
  end

  def self.count_unplanned
    return Event.unplanned_events.count
  end

end

app/models/event_contact.rb
class EventContact < ApplicationRecord
  belongs_to :event
  belongs_to :person
  validates_uniqueness_of :role, scope: [:event_id, :person_id]

  def name
    return self.event.name + "::" + self.person.name
  end

  def self.contacts_for_event event
    return EventContact.where event: event
  end

end

app/models/media_item.rb
class MediaItem < ApplicationRecord
    has_many :task_media_items
end

app/models/people_list.rb
class PeopleList < ApplicationRecord
end

app/models/person.rb
class Person < BasicEntity

  def name
    "#{self.first_name} #{self.last_name}"
  end
  
  def user
    User.find_by(person_id: self.id)
  end
  
  def active_tasks
    if self.user
      return Task.user_tasks(self.user) 
    else
      return []
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :event
  belongs_to :audience
  belongs_to :destination
  belongs_to :owner, class_name: "User"

  def days_to_start
    return (self.start_date && self.start_date > Date.today) ? (self.start_date - Date.today).to_i : 0;
  end

  def days_to_end
    return self.end_date > Date.today ? (self.end_date - Date.today).to_i : 0;
  end

  def self.active_tasks 
    Task.where "end_date >= ?", Date.today.to_date
  end

  def self.past_tasks 
    Task.where "end_date < ?", Date.today.to_date
  end

  def self.user_tasks user
    Task.where "owner_id = ? AND end_date >= ?", user.id, Date.today.to_date
  end

  def self.destination_tasks destination
    Task.where "destination_id = ? AND end_date >= ?", destination.id, Date.today.to_date
  end

  def self.audience_tasks audience
    Task.where "audience_id = ? AND end_date >= ?", audience.id, Date.today.to_date
  end

end

app/models/task_media_item.rb
class TaskMediaItem < ApplicationRecord
  belongs_to :task
  belongs_to :media_item
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :person

  def name
    return self.person.blank? ? " " : self.person.name; 
  end

  def authenticate pwd
    pwd == self.password ? true : false 
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :check_for_user!
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :first_name, :last_name, :email, :mobile_phone)
    end
end

app/helpers/audiences_helper.rb
module AudiencesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def check_for_user!
    if logged_in?
      return true
    else
      redirect_to login_path
    end
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/people/_cards.html.erb
<div class="col-md-12 panel panel-default">
  <div class="panel-body">

<% people.each do |person| %>
  <div class="col-md-4">
    <div class="panel panel-default item-card">
      <div class="panel-heading">
        <span class="h4"><%= link_to person.name, person_path(person) %></span>
        <% if !person.user.nil? %>
          <span class="pull-right small text-center">
            <span class="h2">
              <%= Task.user_tasks(person.user).count %>
            </span><br />
            <%= link_to "task(s)", user_tasks_path(user: person.user) %>
          </span>
        <% end %>
        <h6><%= person.mobile_phone %>
      </div>
      <div class="panel-body item-card-body">
        <%= person.email %> 
      </div>
    </div>
  </div>
<% end %>

  </div>
</div>

app/views/people/_form.html.erb
<%= simple_form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email, as: :email %>
    <%= f.input :mobile_phone, as: :tel %>
    <%= f.button :submit %>
<% end %>

app/views/people/_list.html.erb
<div class="list-group">
  <% people.each do |person| %>
    <%= link_to person.name, person_path(person), class: "list-group-item" %>
  <% end %>
</div>

app/views/people/_table.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Mobile phone</th>
    </tr>
  </thead>

  <tbody>
    <% people.each do |person| %>
      <tr>
        <td><%= link_to person.name, person_path(person) %></td>
        <td><%= person.email %></td>
        <td><%= person.mobile_phone %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/people/edit.html.erb
<div class="container">
  <p></p>
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        Editing <%= @person.name %>
      </div>
      <div class="panel-body">
        <%= render 'form', person: @person %>
        <%= link_to 'Cancel', people_path %>
      </div>
    </div>
  </div>
</div>

app/views/people/index.html.erb
<div class="col-sm-2">
  <div class="row">
    <div class="list-group">
      <%= link_to "Manage Users", users_path, method: :get, class: "list-group-item" %>
    </div>
  </div>
</div>

<div class="col-md-10">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        People
        <span class="badge"><%= @people.count %> </span>
        <span style="float: right">
            <a href="#peopleTable" class="label label-default" data-toggle="tab">
              <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            </a>
            <a href="#peopleCards" class="label label-default" data-toggle="tab">
              <span class="glyphicon glyphicon-th" aria-hidden="true"></span>
            </a>
          <%= link_to 'New Person', new_person_path, class: "label label-default" %> 
        </span>
      </div>
      <div class="tab-content">
        <div id="peopleCards" class="tab-pane active">
          <%= render 'cards', people: @people %>
        </div>
        <div id="peopleTable" class="tab-pane">
          <%= render 'table', people: @people %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/people/new.html.erb
<div class="container">
  <p></p>
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        New Person
      </div>
      <div class="panel-body">
        <%= render 'form', person: @person %>
      </div>
    </div>
  </div>
</div>

app/views/people/show.html.erb
<div class="col-sm-2">
  <div class="row">
    <div class="list-group-title">
      <span class="text-uppercase h5">People</span>
      <span class="pull-right">
        <%= link_to 'New', new_person_path, class: "label label-default" %> 
      </span>
    </div>
    <%= render 'list', people: Person.all %>
  </div>
</div>

<div class="col-md-10">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading entity-heading">
        <span class="h1" style="margin-right:10px;"><%= @person.name %></span>
        <%= link_to 'Edit', edit_person_path(@person), class: "label label-default" %> 
          <%= link_to 'Delete', @person, method: :delete, data: { confirm: 'Are you sure?' }, class: "label label-default" %>
        <p><%= @person.email %></p>
        <p><%= @person.mobile_phone %></p>
      </div>
      <div class="panel-body">
        <% @tasks = @person.active_tasks %>
        <% @tasks_title = @person.name + " Active Tasks" %>
        <%= render 'tasks/viewer' %>
      </div>
    </div>
  </div>
</div>