config/routes.rb
Rails.application.routes.draw do
  get      '/login',   to: 'sessions#new'
  post     '/login',   to: 'sessions#create'
  delete   '/logout',  to: 'sessions#destroy'

  root 'dashboard#index'
  resources :audiences
  resources :tasks do
    collection do
      get :active
      get :past
      get :user
      get :destination
      get :audience
    end
  end
  resources :event_contacts
  resources :media_items
  resources :destinations do
    collection do
      get :destination_type
    end
  end
  resources :destination_types
  resources :users
  resources :events do
    collection do
      get :active
      get :past
      get :planned
      get :unplanned
    end
  end
  resources :people_lists
  resources :tags
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/audience.rb
class Audience < ApplicationRecord

  def active_tasks
    return Task.audience_tasks(self)
  end
end

app/models/basic_entity.rb
class BasicEntity < ApplicationRecord
    self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :destination_type

  def active_tasks
    return Task.destination_tasks(self);
  end

end

app/models/destination_type.rb
class DestinationType < ApplicationRecord

  def destinations
    return Destination.where "destination_type_id = ?", self.id
  end
end

app/models/entity_tag.rb
class EntityTag < ApplicationRecord
  belongs_to :basic_entity
  belongs_to :tag
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :tasks

  def start_date_pretty
    return self.start_date.strftime("%m/%d/%Y")
  end

  def start_time_pretty
    return self.start_time.strftime("%I:%M:%S %p")
  end

  def start_date_and_time
    self.start_date && self.start_time ? self.start_date.strftime("%m/%d/%Y") + " " + self.start_time.strftime("%I:%M:%S %p") : ""
  end

  def end_date_pretty
    return self.end_date.strftime("%m/%d/%Y")
  end

  def end_time_pretty
    return self.end_time.strftime("%I:%M:%S %p")
  end

  def end_date_and_time
    return self.end_date.strftime("%m/%d/%Y") + " " + self.end_time.strftime("%I:%M:%S %p")
  end

  def days_to_start
    return self.start_date > Date.today ? (self.start_date - Date.today).to_i : 0;
  end

  def days_to_end
    return self.end_date > Date.today ? (self.end_date - Date.today).to_i : 0;
  end

  def self.active_events
    return Event.where "end_date >= ?", Date.today.to_date
  end

  def self.past_events
    return Event.where "end_date < ?", Date.today.to_date
  end

  def self.planned_events
    event_array = []
    Event.active_events.each do |active_event|
      if !active_event.tasks.blank? 
        event_array << active_event
      end
    end
    return event_array
  end

  def self.count_planned
    return Event.planned_events.count
  end

  def self.unplanned_events
    event_array = []
    Event.active_events.each do |active_event|
      if active_event.tasks.blank? 
        event_array << active_event
      end
    end
    return event_array
  end

  def self.count_unplanned
    return Event.unplanned_events.count
  end

end

app/models/event_contact.rb
class EventContact < ApplicationRecord
  belongs_to :event
  belongs_to :person
  validates_uniqueness_of :role, scope: [:event_id, :person_id]

  def name
    return self.event.name + "::" + self.person.name
  end

  def self.contacts_for_event event
    return EventContact.where event: event
  end

end

app/models/media_item.rb
class MediaItem < ApplicationRecord
    has_many :task_media_items
end

app/models/people_list.rb
class PeopleList < ApplicationRecord
end

app/models/person.rb
class Person < BasicEntity

  def name
    "#{self.first_name} #{self.last_name}"
  end
  
  def user
    User.find_by(person_id: self.id)
  end
  
  def active_tasks
    if self.user
      return Task.user_tasks(self.user) 
    else
      return []
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :event
  belongs_to :audience
  belongs_to :destination
  belongs_to :owner, class_name: "User"

  def days_to_start
    return (self.start_date && self.start_date > Date.today) ? (self.start_date - Date.today).to_i : 0;
  end

  def days_to_end
    return self.end_date > Date.today ? (self.end_date - Date.today).to_i : 0;
  end

  def self.active_tasks 
    Task.where "end_date >= ?", Date.today.to_date
  end

  def self.past_tasks 
    Task.where "end_date < ?", Date.today.to_date
  end

  def self.user_tasks user
    Task.where "owner_id = ? AND end_date >= ?", user.id, Date.today.to_date
  end

  def self.destination_tasks destination
    Task.where "destination_id = ? AND end_date >= ?", destination.id, Date.today.to_date
  end

  def self.audience_tasks audience
    Task.where "audience_id = ? AND end_date >= ?", audience.id, Date.today.to_date
  end

end

app/models/task_media_item.rb
class TaskMediaItem < ApplicationRecord
  belongs_to :task
  belongs_to :media_item
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :person

  def name
    return self.person.blank? ? " " : self.person.name; 
  end

  def authenticate pwd
    pwd == self.password ? true : false 
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :check_for_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @tasks_title = "All Tasks"
  end

  def active
    @tasks = Task.active_tasks
    @tasks_title = "Active Tasks"
    render action: :index
  end

  def past
    @tasks = Task.past_tasks
    @tasks_title = "Past Tasks"
    render action: :index
  end

  def user
    selected_user = User.find(params[:user])
    @tasks = Task.user_tasks(selected_user)
    @tasks_title = (selected_user.id == session[:user_id]) ? "My Tasks" : selected_user.name + " Tasks"
    render action: :index
  end

  def destination 
    selected_destination = Destination.find(params[:destination])
    @tasks = Task.destination_tasks(selected_destination)
    @tasks_title = selected_destination.name + " Tasks"
    render action: :index
  end

  def audience
    selected_audience = Audience.find(params[:audience])
    @tasks = Task.audience_tasks(selected_audience)
    @tasks_title = selected_audience.name + " Tasks"
    render action: :index
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :start_date, :end_date, :event_id, :audience_id, :destination_id, :owner_id)
    end
end

app/helpers/audiences_helper.rb
module AudiencesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def check_for_user!
    if logged_in?
      return true
    else
      redirect_to login_path
    end
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tasks/_cards.html.erb
<div class="col-md-12 panel panel-default">
  <div class="panel-body">

<% tasks.each do |task| %>
  <div class="col-md-4">
    <div class="panel panel-default item-card">
      <div class="panel-heading">
        <span class="h4"><%= link_to task.name, task_path(task) %></span>
        <% if task.start_date %>
        <span class="pull-right small text-center">
          <span class="h2">
            <%= task.days_to_start %>
          </span>
          <br /> days
        </span>
        <h6><%= task.start_date.strftime("%A, %h %d %Y") %></h6>
        <% end %>
      </div>
      <div class="panel-body item-card-body">
        <div>
          Owner: <%= link_to task.owner.name, person_path(task.owner.person) %>
        </div>
        <div>
          Audience: <%= link_to task.audience.name, audience_path(task.audience) %>
        </div>
        <div>
          Destination: <%= link_to task.destination.name, destination_path(task.destination) %>
        </div>
      </div>
    </div>
  </div>
<% end %>

  </div>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.association :event, collection: Event.active_events %>
    <%= f.input :name %>
    <%= f.association :audience%>
    <%= f.association :destination%>
    <%= f.association :owner, label_method: :name %>
    <%= f.label "Start Date" %>
    <%= f.text_field :start_date, :placeholder => "Start Date", :class => "form-control datepicker", :data => { :provide => "datepicker"} %>
    <%= f.label "End Date" %>
    <%= f.text_field :end_date, :placeholder => "End Date", :class => "form-control datepicker", :data => { :provide => "datepicker"} %>
    <p></p>
    <%= f.button :submit %>
<% end %>

app/views/tasks/_list.html.erb
<div class="list-group">
  <% Task.all.each do |task| %>
    <%= link_to task.name, task_path(task), class: "list-group-item" %>
  <% end %>
</div>

app/views/tasks/_table.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start</th>
      <th>End</th>
      <th>Event</th>
      <th>Audience</th>
      <th>Destination</th>
      <th>Owner</th>
    </tr>
  </thead>

  <tbody>
    <% tasks.each do |task| %>
      <tr>
        <td><%= link_to task.name, task_path(task) %></td>
        <td><%= task.start_date %></td>
        <td><%= task.end_date %></td>
        <td><%= link_to task.event.name, event_path(task.event) %></td>
        <td><%= task.audience.name %></td>
        <td><%= task.destination.name %></td>
        <td><%= link_to task.owner.person.name, person_path(task.owner.person) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/_viewer.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= @tasks_title %>
    <span class="badge"><%= @tasks.count %> </span>
    <span style="float: right">
      <a href="#taskTable" class="label label-default" data-toggle="tab">
        <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
      </a>
      <a href="#taskCard" class="label label-default" data-toggle="tab">
        <span class="glyphicon glyphicon-th" aria-hidden="true"></span>
      </a>
      <%= link_to new_task_path, class: "label label-default" do %>
        <span class="glyphicon glyphicon-plus"></span>
        New Task
      <% end %>
    </span>
  </div>
  <div class="tab-content">
    <div id="taskCard" class="tab-pane active">
      <%= render 'tasks/cards', tasks: @tasks %>
    </div>
    <div id="taskTable" class="tab-pane">
      <%= render 'tasks/table', tasks: @tasks %>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="container">
  <p></p>
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        Editing Task
      </div>
      <div class="panel-body">
        <%= render 'form', task: @task %>
        <%= link_to 'Cancel', tasks_path %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="col-sm-2">
  <div class="row">
    <div class="list-group">
      <div class="list-group-title">Related Items</div>
      <%= link_to "Destinations", destinations_path, class: "list-group-item" %>
      <%= link_to "Audiences", audiences_path, class: "list-group-item" %>
    </div>
    <div class="list-group">
      <div class="list-group-title">Filters</div>
      <%= link_to "My Tasks", user_tasks_path(user: current_user), class: "list-group-item" %>
      <%= link_to "Active Tasks", active_tasks_path, class: "list-group-item" %>
      <%= link_to "Past Tasks", past_tasks_path, class: "list-group-item" %>
      <%= link_to "All Tasks", tasks_path, class: "list-group-item" %>
    </div>
  </div>
</div>

<div class="col-md-10">
  <div class="row">
    <%= render 'viewer', tasks: @tasks, tasks_title: @tasks_title %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <p></p>
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        New Task
      </div>
      <div class="panel-body">
        <%= render 'form', task: @task %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="col-sm-2">
  <div class="row">
    <div class="list-group-title">
      <span class="text-uppercase h5">Tasks</span>
      <span class="pull-right">
        <%= link_to 'New', new_task_path, class: "label label-default" %> 
      </span>
    </div>
    <%= render 'list', tasks: Task.all %>
  </div>
</div>

<div class="col-md-10">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading entity-heading">
        <span class="h1" style="margin-right:10px;"><%= @task.name %></span>
          <%= link_to 'Edit', edit_task_path(@task), class: "label label-default" %> 
          <%= link_to 'Delete', @task, method: :delete, data: { confirm: 'Are you sure?' }, class: "label label-default" %>
          <p> <%= link_to @task.event.name, event_path(@task.event)%> </p>
      </div>
      <div class="panel-body">
        <table class="table">
          <tr>
            <th>Publish</th>
            <th>Stop</th>
            <th>Owner</th>
            <th>Destination</th>
            <th>Audience</th>
          </tr>
          <tr>
            <td><%= @task.start_date %></td>
            <td><%= @task.end_date %></td>
            <td><%= link_to @task.owner.name, user_path(@task.owner) %></td>
            <td><%= link_to @task.destination.name, destination_path(@task.destination) %></td>
            <td><%= link_to @task.audience.name, audience_path(@task.audience) %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>