config/routes.rb
Rails.application.routes.draw do
  get      '/login',   to: 'sessions#new'
  post     '/login',   to: 'sessions#create'
  delete   '/logout',  to: 'sessions#destroy'

  root 'dashboard#index'
  resources :audiences
  resources :tasks do
    collection do
      get :active
      get :past
      get :user
      get :destination
      get :audience
    end
  end
  resources :event_contacts
  resources :media_items
  resources :destinations do
    collection do
      get :destination_type
    end
  end
  resources :destination_types
  resources :users
  resources :events do
    collection do
      get :active
      get :past
      get :planned
      get :unplanned
    end
  end
  resources :people_lists
  resources :tags
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/audience.rb
class Audience < ApplicationRecord

  def active_tasks
    return Task.audience_tasks(self)
  end
end

app/models/basic_entity.rb
class BasicEntity < ApplicationRecord
    self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :destination_type

  def active_tasks
    return Task.destination_tasks(self);
  end

end

app/models/destination_type.rb
class DestinationType < ApplicationRecord

  def destinations
    return Destination.where "destination_type_id = ?", self.id
  end
end

app/models/entity_tag.rb
class EntityTag < ApplicationRecord
  belongs_to :basic_entity
  belongs_to :tag
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :tasks

  def start_date_pretty
    return self.start_date.strftime("%m/%d/%Y")
  end

  def start_time_pretty
    return self.start_time.strftime("%I:%M:%S %p")
  end

  def start_date_and_time
    self.start_date && self.start_time ? self.start_date.strftime("%m/%d/%Y") + " " + self.start_time.strftime("%I:%M:%S %p") : ""
  end

  def end_date_pretty
    return self.end_date.strftime("%m/%d/%Y")
  end

  def end_time_pretty
    return self.end_time.strftime("%I:%M:%S %p")
  end

  def end_date_and_time
    return self.end_date.strftime("%m/%d/%Y") + " " + self.end_time.strftime("%I:%M:%S %p")
  end

  def days_to_start
    return self.start_date > Date.today ? (self.start_date - Date.today).to_i : 0;
  end

  def days_to_end
    return self.end_date > Date.today ? (self.end_date - Date.today).to_i : 0;
  end

  def self.active_events
    return Event.where "end_date >= ?", Date.today.to_date
  end

  def self.past_events
    return Event.where "end_date < ?", Date.today.to_date
  end

  def self.planned_events
    event_array = []
    Event.active_events.each do |active_event|
      if !active_event.tasks.blank? 
        event_array << active_event
      end
    end
    return event_array
  end

  def self.count_planned
    return Event.planned_events.count
  end

  def self.unplanned_events
    event_array = []
    Event.active_events.each do |active_event|
      if active_event.tasks.blank? 
        event_array << active_event
      end
    end
    return event_array
  end

  def self.count_unplanned
    return Event.unplanned_events.count
  end

end

app/models/event_contact.rb
class EventContact < ApplicationRecord
  belongs_to :event
  belongs_to :person
  validates_uniqueness_of :role, scope: [:event_id, :person_id]

  def name
    return self.event.name + "::" + self.person.name
  end

  def self.contacts_for_event event
    return EventContact.where event: event
  end

end

app/models/media_item.rb
class MediaItem < ApplicationRecord
    has_many :task_media_items
end

app/models/people_list.rb
class PeopleList < ApplicationRecord
end

app/models/person.rb
class Person < BasicEntity

  def name
    "#{self.first_name} #{self.last_name}"
  end
  
  def user
    User.find_by(person_id: self.id)
  end
  
  def active_tasks
    if self.user
      return Task.user_tasks(self.user) 
    else
      return []
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :event
  belongs_to :audience
  belongs_to :destination
  belongs_to :owner, class_name: "User"

  def days_to_start
    return (self.start_date && self.start_date > Date.today) ? (self.start_date - Date.today).to_i : 0;
  end

  def days_to_end
    return self.end_date > Date.today ? (self.end_date - Date.today).to_i : 0;
  end

  def self.active_tasks 
    Task.where "end_date >= ?", Date.today.to_date
  end

  def self.past_tasks 
    Task.where "end_date < ?", Date.today.to_date
  end

  def self.user_tasks user
    Task.where "owner_id = ? AND end_date >= ?", user.id, Date.today.to_date
  end

  def self.destination_tasks destination
    Task.where "destination_id = ? AND end_date >= ?", destination.id, Date.today.to_date
  end

  def self.audience_tasks audience
    Task.where "audience_id = ? AND end_date >= ?", audience.id, Date.today.to_date
  end

end

app/models/task_media_item.rb
class TaskMediaItem < ApplicationRecord
  belongs_to :task
  belongs_to :media_item
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :person

  def name
    return self.person.blank? ? " " : self.person.name; 
  end

  def authenticate pwd
    pwd == self.password ? true : false 
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :check_for_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @events_title = "All Events"
  end

  def active
    @events = Event.active_events
    @events_title = "Active Events"
    render action: :index
  end

  def past
    @events = Event.past_events
    @events_title = "Past Events"
    render action: :index
  end

  def planned
    @events = Event.planned_events
    @events_title = "Planned Events"
    render action: :index
  end

  def unplanned
    @events = Event.unplanned_events
    @events_title = "Unplanned Events"
    render action: :index
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :start_date, :start_time, :end_date, :end_time, :all_day, :public)
    end
end

app/helpers/audiences_helper.rb
module AudiencesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def check_for_user!
    if logged_in?
      return true
    else
      redirect_to login_path
    end
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_cards.html.erb
<div class="col-md-12 panel panel-default">
  <div class="panel-body">

<% events.each do |event| %>
  <div class="col-md-4">
    <div class="panel panel-default item-card">
      <div class="panel-heading">
        <span class="h4"><%= link_to event.name, event_path(event) %></span>
        <span class="pull-right small text-center">
          <span class="h2"><%= event.days_to_start %></span><br />
          days</span>
        <h6><%= event.start_date_and_time %></h6>
      </div>
      <div class="panel-body item-card-body">
        <%= event.description %>
      </div>
    </div>
  </div>
<% end %>

  </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :name, label: 'Name' %>
    <%= f.input :description, label: 'Description' %>
    <%= f.label "Start Date" %>
    <%= f.input :start_date, label: 'Start Date' %>
    <%= f.input :start_time, label: 'Start Time' %>
    <%= f.label "End Date" %>
    <%= f.input :end_date, label: 'End Date' %>
    <%= f.input :end_time, label: 'End Time' %>
    <p></p>
    <%= f.input :all_day %>
    <%= f.input :public %>
    <%= f.button :submit %>

<% end %>

app/views/events/_list.html.erb
<div class="list-group">
  <% events.each do |event| %>
    <%= link_to event.name, event_path(event), class: "list-group-item" %>
  <% end %>
</div>

app/views/events/_table.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>All Day</th>
      <th>Start</th>
      <th>End</th>
      <th>Public</th>
    </tr>
  </thead>

  <tbody>
    <% events.each do |event| %>
      <tr>
        <td><%= link_to event.name, event_path(event) %></td>
        <td><%= event.description %></td>
        <td><%= event.all_day ? "yes" : "no" %></td>
        <td><%= event.start_date_and_time %></td>
        <td><%= event.end_date_and_time %></td>
        <td><%= event.public ? "yes" : "no" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/_viewer.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= @events_title %>
    <span class="badge"><%= @events.count %> </span>
    <div style="float: right">
        <a href="#eventTable" class="label label-default" data-toggle="tab">
          <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
        </a>
        <a href="#eventCards" class="label label-default" data-toggle="tab">
          <span class="glyphicon glyphicon-th" aria-hidden="true"></span>
        </a>
        <%= link_to new_event_path, class: "label label-default" do %>
          <span class="glyphicon glyphicon-plus"></span>
          New Event
        <% end %>
    </div>
  </div>
  <div class="tab-content">
    <div id="eventCards" class="tab-pane active">
      <%= render 'events/cards', events: @events %>
    </div>
    <div id="eventTable" class="tab-pane">
      <%= render 'events/table', events: @events %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container">
  <p></p>
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        Editing Event
      </div>
      <div class="panel-body">
        <%= render 'form', event: @event %>
        <%= link_to 'Cancel', events_path %>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="col-sm-2">
  <div class="row">
    <div class="list-group">
      <%= link_to "Planned Events", planned_events_path, class: "list-group-item" %>
      <%= link_to "Unplanned Events", unplanned_events_path, class: "list-group-item" %>
      <%= link_to "Active Events", active_events_path, class: "list-group-item" %>
      <%= link_to "Past Events", past_events_path, class: "list-group-item" %>
      <%= link_to "All Events", events_path, class: "list-group-item" %>
    </div>
  </div>
</div>

<div class="col-md-10">
  <div class="row">
    <%= render 'viewer', events: @events, events_title: @events_title %>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <p></p>
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        New Event
      </div>
      <div class="panel-body">
        <%= render 'form', event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="col-sm-2">
  <div class="row">
    <div class="list-group-title">
      <span class="text-uppercase h5">Events</span>
      <span class="pull-right">
        <%= link_to 'New', new_event_path, class: "label label-default" %> 
      </span>
    </div>
    <%= render 'list', events: Event.all %>
  </div>
</div>

<div class="col-md-10">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading entity-heading">
        <span class="h1" style="margin-right:10px;"><%= @event.name %></span>
          <%= link_to 'Edit', edit_event_path(@event), class: "label label-default" %> 
          <%= link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' }, class: "label label-default" %>
          <div class="col-md-8 col-lg-10">
            <p></p>
            <table class="table table-condensed">
              <tr>
                <th>All Day</th>
                <th>Start</th>
                <th>End</th>
                <th>Public</th>
              </tr>
              <tr>
                <td><%= @event.all_day ? "yes" : "no" %></td>
                <td><%= @event.start_date_and_time %></td>
                <td><%= @event.end_date_and_time  %></td>
                <td><%= @event.public ? "yes" : "no" %></td>
              </tr>
            </table>
              <p> <%= @event.description %></p>
          </div>
      </div>
      <div class="panel-body">
        <ul class="nav nav-tabs">
          <li role="presentation" class="active"><a href="#tasks" data-toggle="tab">Tasks</a></li>
          <li role="presentation"><a href="#contacts" data-toggle="tab">Contacts</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="tasks">
            <div class="containter">
              <% @tasks = @event.tasks %>
              <% @tasks_title =  "Event Tasks" %>
              <%= render 'tasks/viewer' %>
            </div>
          </div>
          <div class="tab-pane" id="contacts">
            <div class="containter">
              <span class="h4">Contacts</span>
              <span style="float: right">
                <%= link_to "New Contact", new_event_contact_path, class: "label label-default" %>
              </span>
              <%= render 'event_contacts/table', event_contacts: EventContact.contacts_for_event(@event) %>
            </div>
          </div>


      </div>
    </div>
  </div>
</div>